@startuml

class Character
class SpellSlot
class Spell
class Character extends Player
Character -[hidden]-> Player

Player +-- SpellSlot
Player +-- Spell

class Character{
    str name
    int level
    str weapon
    str secondary
    str armor
    int health
    int mana
    levelUp()
    updateWeapon()
    updateSecondary()
    updateArmor()
    updateInventory()
}

class Player{
    enum JobType
    jobChange()
    defaultJobSpells()
}

class Spell{
    str name
    int damage
    int cost
    int effect  
}

class SpellSlot{
    list spells
    addSpell()
}
@enduml